"""Generate 3D ground tile GLBs from existing 2D tile textures using Hunyuan3D v2.0.

Takes the existing seamless ground textures (PNG) generated by generate_isometric_tiles.py
and converts them to textured 3D ground meshes (GLB) via the Hunyuan3D v2.0 pipeline.

The 3D tiles add subtle height variation (cobblestones, rough stone, wood grain, etc.)
with baked color textures from multi-view rendering.

Usage:
    python generate_3d_ground_tiles.py [--dry-run] [--terrain TYPE] [--list]
    python generate_3d_ground_tiles.py --terrain frost_forest_floor
    python generate_3d_ground_tiles.py --force  # regenerate existing GLBs
"""

import argparse
import copy
import hashlib
import json
import logging
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

COMFYUI_URL = "http://127.0.0.1:8188"
GODOT_PROJECT = Path("D:/Projects/berserkr-godot")
TILESET_DIR = GODOT_PROJECT / "games" / "berserkr" / "assets" / "tilesets"
INPUT_DIR = TILESET_DIR / "generated"  # 2D tile PNGs live here
OUTPUT_DIR = TILESET_DIR / "3d"  # 3D GLBs go here

# Workflow template — geometry-only (texture rasterizer not compiled, so we export
# untextured GLBs and apply existing 2D tile textures in Godot instead)
WORKFLOW_PATH = Path(__file__).parent.parent.parent.parent / "workflows" / "mcp" / "hunyuan3d_v20_geometry_only.json"

# Terrain types for classification (PBR would need v2.5 model)
TERRAIN_TYPES = [
    "frost_forest_floor", "sacred_clearing", "dirt_road", "snow_field",
    "village_ground", "wood_floor_interior", "stone_floor_interior",
    "forge_floor", "cave_floor", "barrow_ground", "graveyard",
]

# Generation parameters tuned for flat ground tiles (not objects).
# Lower octree/faces = flatter geometry, faster generation.
GROUND_TILE_PARAMS = {
    "guidance_scale": 4.0,    # Lower guidance = less extreme geometry
    "steps": 30,              # Fewer steps = faster, still good quality
    "octree_resolution": 256, # Lower res = smoother/flatter mesh
    "max_faces": 10000,       # Low poly — it's just ground
}


def seed_for_name(name: str) -> int:
    return int(hashlib.md5(name.encode()).hexdigest()[:8], 16)


def load_workflow() -> dict:
    """Load the Hunyuan3D v2.5 PBR workflow template."""
    if not WORKFLOW_PATH.exists():
        logger.error("Workflow not found: %s", WORKFLOW_PATH)
        sys.exit(1)
    with open(WORKFLOW_PATH) as f:
        return json.load(f)


def build_workflow(template: dict, image_path: str, terrain_type: str,
                   filename_prefix: str, seed: int) -> dict:
    """Build a concrete workflow from the v2.0 template with parameters filled in."""
    wf = copy.deepcopy(template)

    # Build a map of all PARAM_* -> concrete values
    param_map = {
        "PARAM_STR_IMAGE_PATH": image_path,
        "PARAM_FLOAT_GUIDANCE_SCALE": GROUND_TILE_PARAMS["guidance_scale"],
        "PARAM_INT_STEPS": GROUND_TILE_PARAMS["steps"],
        "PARAM_INT_SEED": seed,
        "PARAM_INT_OCTREE_RESOLUTION": GROUND_TILE_PARAMS["octree_resolution"],
        "PARAM_INT_MAX_FACES": GROUND_TILE_PARAMS["max_faces"],
    }

    # Replace ALL PARAM_* placeholders across every node
    for node_id, node in wf.items():
        inputs = node.get("inputs", {})
        for key, val in inputs.items():
            if isinstance(val, str) and val in param_map:
                inputs[key] = param_map[val]

    # Set export filename prefix (geometry-only: node 11 is the only export)
    wf["11"]["inputs"]["filename_prefix"] = f"3D/ground_tile_{filename_prefix}"

    return wf


def check_comfyui() -> bool:
    try:
        with urllib.request.urlopen(f"{COMFYUI_URL}/system_stats", timeout=5) as resp:
            return resp.status == 200
    except Exception:
        return False


def upload_image(image_path: Path) -> str:
    """Upload an image to ComfyUI and return the uploaded filename."""
    import mimetypes
    boundary = "----FormBoundary" + hashlib.md5(str(time.time()).encode()).hexdigest()[:16]
    content_type = mimetypes.guess_type(str(image_path))[0] or "image/png"

    with open(image_path, "rb") as f:
        file_data = f.read()

    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="image"; filename="{image_path.name}"\r\n'
        f"Content-Type: {content_type}\r\n\r\n"
    ).encode() + file_data + f"\r\n--{boundary}--\r\n".encode()

    req = urllib.request.Request(
        f"{COMFYUI_URL}/upload/image",
        data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read())
    return data.get("name", image_path.name)


def queue_prompt(workflow: dict) -> str:
    payload = json.dumps({"prompt": workflow}).encode()
    req = urllib.request.Request(
        f"{COMFYUI_URL}/prompt",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
        return data["prompt_id"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8", errors="replace")
        logger.error("  ComfyUI rejected workflow: %s", error_body[:500])
        raise


def poll_history(prompt_id: str, timeout: int = 600, interval: int = 10) -> dict | None:
    """Poll ComfyUI history for workflow completion. Longer timeout for 3D generation."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(f"{COMFYUI_URL}/history/{prompt_id}", timeout=10) as resp:
                data = json.loads(resp.read())
            if prompt_id in data:
                entry = data[prompt_id]
                status = entry.get("status", {})
                if status.get("status_str") == "success" or status.get("completed", False):
                    return entry
                if status.get("status_str") == "error":
                    logger.error("  Workflow error: %s", status)
                    return None
        except Exception:
            pass
        time.sleep(interval)
    logger.error("  Timed out waiting for workflow %s", prompt_id)
    return None


COMFYUI_OUTPUT_DIR = Path("D:/Projects/ComfyUI/output")


def copy_glb_from_output(filename_prefix: str, output_path: Path) -> bool:
    """Copy the generated GLB from ComfyUI's output/3D/ directory.

    Hy3DExportMesh writes files directly to disk (not through the API output system),
    so we copy from ComfyUI's output folder instead of downloading via HTTP.
    """
    glb_dir = COMFYUI_OUTPUT_DIR / "3D"
    if not glb_dir.exists():
        logger.error("  ComfyUI 3D output dir not found: %s", glb_dir)
        return False

    # Find the GLB matching our prefix (ComfyUI appends _00001_.glb etc.)
    candidates = sorted(glb_dir.glob(f"{filename_prefix}_*.glb"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        logger.error("  No GLB found matching prefix: %s", filename_prefix)
        return False

    source = candidates[0]  # Most recent matching file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    import shutil
    shutil.copy2(source, output_path)
    size_kb = output_path.stat().st_size // 1024
    logger.info("  Copied: %s -> %s (%d KB)", source.name, output_path.name, size_kb)
    return True


def get_tiles_to_generate(terrain_filter: str | None = None) -> list[dict]:
    """Scan INPUT_DIR for existing 2D tile PNGs and build generation list."""
    tiles = []
    if not INPUT_DIR.exists():
        logger.error("Input directory not found: %s", INPUT_DIR)
        return tiles

    for png_file in sorted(INPUT_DIR.glob("*.png")):
        name = png_file.stem  # e.g. "frost_forest_floor" or "frost_forest_floor_dense"

        # Determine terrain type (strip variant suffix)
        terrain_type = name
        for known_type in TERRAIN_TYPES:
            if name == known_type or name.startswith(known_type + "_"):
                terrain_type = known_type
                break

        if terrain_filter and terrain_type != terrain_filter:
            continue

        tiles.append({
            "name": name,
            "terrain_type": terrain_type,
            "input_path": png_file,
            "output_path": OUTPUT_DIR / f"{name}.glb",
        })

    return tiles


def main():
    parser = argparse.ArgumentParser(description="Generate 3D ground tiles from 2D textures")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be generated")
    parser.add_argument("--terrain", type=str, default=None, help="Only generate for this terrain type")
    parser.add_argument("--force", action="store_true", help="Regenerate even if GLB exists")
    parser.add_argument("--list", action="store_true", help="List available tiles and exit")
    args = parser.parse_args()

    tiles = get_tiles_to_generate(args.terrain)
    if not tiles:
        logger.error("No tiles found to generate")
        sys.exit(1)

    if args.list:
        logger.info("Available tiles (%d):", len(tiles))
        for t in tiles:
            exists = "EXISTS" if t["output_path"].exists() else "MISSING"
            logger.info("  %-40s [%s] (%s)", t["name"], t["terrain_type"], exists)
        return

    if not args.dry_run and not check_comfyui():
        logger.error("ComfyUI is not running at %s", COMFYUI_URL)
        sys.exit(1)

    workflow_template = load_workflow()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    generated = 0
    failed = 0
    skipped = 0
    start_time = time.time()

    logger.info("Generating 3D ground tiles: %d tiles", len(tiles))
    logger.info("Workflow: %s", WORKFLOW_PATH.name)
    logger.info("Output: %s", OUTPUT_DIR)
    logger.info("")

    for i, tile in enumerate(tiles, 1):
        label = f"{tile['name']} ({tile['terrain_type']})"
        logger.info("[%d/%d] %s", i, len(tiles), label)

        if not args.force and tile["output_path"].exists():
            logger.info("  Already exists, skipping (use --force to regenerate)")
            skipped += 1
            continue

        if args.dry_run:
            logger.info("  DRY RUN — input: %s", tile["input_path"].name)
            logger.info("  Terrain: %s, Seed: %d", tile["terrain_type"],
                        seed_for_name(f"berserkr_3d_tile_{tile['name']}") + 7000)
            logger.info("  Output: %s", tile["output_path"])
            skipped += 1
            continue

        # Upload the 2D texture to ComfyUI
        try:
            uploaded_name = upload_image(tile["input_path"])
            logger.info("  Uploaded: %s", uploaded_name)
        except Exception as e:
            logger.error("  Upload failed: %s", e)
            failed += 1
            continue

        seed = seed_for_name(f"berserkr_3d_tile_{tile['name']}") + 7000
        workflow = build_workflow(
            workflow_template,
            image_path=uploaded_name,
            terrain_type=tile["terrain_type"],
            filename_prefix=tile["name"],
            seed=seed,
        )

        # The filename prefix used in the workflow for finding the output file
        export_prefix = f"ground_tile_{tile['name']}"

        try:
            prompt_id = queue_prompt(workflow)
            logger.info("  Queued: %s (this may take 3-5 minutes)", prompt_id[:11])

            history = poll_history(prompt_id, timeout=600, interval=10)
            if history and copy_glb_from_output(export_prefix, tile["output_path"]):
                generated += 1
            else:
                logger.error("  FAILED: %s", label)
                failed += 1
        except Exception as e:
            logger.error("  FAILED: %s — %s", label, e)
            failed += 1

        # Brief pause between generations to let GPU cool
        if i < len(tiles):
            time.sleep(3)

    elapsed = time.time() - start_time
    logger.info("")
    logger.info("=" * 60)
    logger.info("COMPLETE — %d generated, %d failed, %d skipped in %.1fs",
                generated, failed, skipped, elapsed)
    if generated > 0:
        logger.info("Output directory: %s", OUTPUT_DIR)
        logger.info("Run Godot reimport to pick up new GLBs")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
